default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: study_app_database_development

test:
  <<: *default
  database: study_app_database_test

production:
  <<: *default
  database: react_rails_api_project_template_production
  username: react_rails_api_project_template
  password: <%= ENV['REACT_RAILS_API_PROJECT_TEMPLATE_DATABASE_PASSWORD'] %>
